### ISSUE TITLE
Issue with decoding the following viewstate

### ISSUE THREAD

**Issue by Gargam** [yuvadm/viewstate#2]
Hello there,

I'm not familiar AT ALL with viewstate but I needed to decode some viewstate from scrapping.

I have viewstate that seems to be valid as it works with http://viewstatedecoder.azurewebsites.net/
but it doesn't with the library.
It raise an exception:

    ViewStateException: Unable to parse remainder of 64615 bytes b'\n\x91\x01\x1e\x04Text\x051<b>Vous n'

Thanks for your time.

Here's the b64 encoded viewstate: https://gist.github.com/yuvadm/09524e56f2c6376e726d4f5b8c87be39

**Comment by yuvadm** [comment]
Looks like there's a problem with this item (in an array) `\n\x91\x01` that according to the online decoder maps to `Color: Color [Salmon]`. I can't find an immedaite reference for kind of markers `0x0a` is, and how to parse the subsequent two bytes. Will look into this.

**Comment by yuvadm** [comment]
In the meantime, I might just add support for the `0x0a` marker with an unknown color value, so that parsing doesn't bork on these values. Expect a fix in an upcoming `v0.3` release.

**Comment by Gargam** [comment]
Ok, I'll test is as soon as it's released :).

**Comment by yuvadm** [comment]
@Gargam fixed on `v0.3` branch, release still pending

**Comment by Gargam** [comment]
@yuvadm Tks, it's now working without any break :).
I see that you had support for another string 0x05 (that was causing some trouble later on when working on a fix of my own).

Nice coincidence that one of the only projects to deal with viewstate is in Python and so young.

**Comment by yuvadm** [comment]
I've actually been thinking about the idea for a few years, but other stuff got in the way :) Now got some motivation to actually implement most of the logic.

Thanks for the issue! Please let me know if you bump into any other problems, more samples are always welcome.
